In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import joblib

In [3]:
import os

os.getcwd()

'C:\\Users\\karan\\HealthInsuranceProject'

In [4]:
os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'Health_insu_premium.ipynb',
 'Health_insu_premium.xlsx',
 'premium_model.pkl',
 'requirements.txt']

In [5]:
# os.listdir('Downloads')

In [6]:
df = pd.read_excel(
    r"C:\Users\karan\HealthInsuranceProject\Health_insu_premium.xlsx"
)

df.head()

,Age,Gender,Region,Marital_status,Physical_Activity,Stress_Level,Number Of Dependants,BMI_Category,Smoking_Status,Employment_Status,Income_Level,Income_Lakhs,Medical History,Insurance_Plan,Annual_Premium_Amount
0,56,Female,Southeast,Unmarried,Medium,Medium,2,Normal,No Smoking,Self-Employed,25L - 40L,37,High blood pressure,Gold,27944
1,38,Female,Northeast,Married,Low,High,5,Overweight,Occasional,Freelancer,10L - 25L,10,No Disease,Silver,21108
2,18,Female,Southwest,Unmarried,Medium,High,0,Normal,No Smoking,Freelancer,<10L,9,No Disease,Bronze,8459
3,55,Male,Northeast,Married,High,Medium,3,Overweight,Occasional,Salaried,<10L,9,Thyroid,Silver,21685
4,22,Male,Southeast,Unmarried,Medium,High,2,Normal,Regular,Self-Employed,10L - 25L,13,High blood pressure & Heart disease,Bronze,15984

In [7]:
df.shape

(10000, 15)

In [8]:
df.columns

Index(['Age', 'Gender', 'Region', 'Marital_status', 'Physical_Activity',
       'Stress_Level', 'Number Of Dependants', 'BMI_Category',
       'Smoking_Status', 'Employment_Status', 'Income_Level', 'Income_Lakhs',
       'Medical History', 'Insurance_Plan', 'Annual_Premium_Amount'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    10000 non-null  int64
 1   Gender                 10000 non-null  object
 2   Region                 10000 non-null  object
 3   Marital_status         10000 non-null  object
 4   Physical_Activity      10000 non-null  object
 5   Stress_Level           10000 non-null  object
 6   Number Of Dependants   10000 non-null  int64
 7   BMI_Category           10000 non-null  object
 8   Smoking_Status         9991 non-null   object
 9   Employment_Status      9993 non-null   object
 10  Income_Level           9982 non-null   object
 11  Income_Lakhs           10000 non-null  int64
 12  Medical History        10000 non-null  object
 13  Insurance_Plan         10000 non-null  object
 14  Annual_Premium_Amount  10000 non-null  int64
dtypes: int64(4), object(11)
memory usage: 1.1+ MB

In [10]:
df.isnull().sum()

Age                       0
Gender                    0
Region                    0
Marital_status            0
Physical_Activity         0
Stress_Level              0
Number Of Dependants      0
BMI_Category              0
Smoking_Status            9
Employment_Status         7
Income_Level             18
Income_Lakhs              0
Medical History           0
Insurance_Plan            0
Annual_Premium_Amount     0
dtype: int64

In [11]:
df.describe()

                Age  Number Of Dependants  Income_Lakhs  Annual_Premium_Amount
count  10000.000000          10000.000000  10000.000000           10000.000000
mean      41.316300              3.192900     23.339900           19505.063900
std       57.971661             21.650454     32.302974            8893.649171
min       18.000000              0.000000      1.000000            3582.000000
25%       24.000000              0.000000      6.000000           11777.750000
50%       37.000000              2.000000     16.000000           19312.000000
75%       50.000000              3.000000     31.000000           26494.500000
max     1178.000000            456.000000    960.000000           45854.000000

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = encoder.fit_transform(df[col])

df.head()

,Age,Gender,Region,Marital_status,Physical_Activity,Stress_Level,Number Of Dependants,BMI_Category,Smoking_Status,Employment_Status,Income_Level,Income_Lakhs,Medical History,Insurance_Plan,Annual_Premium_Amount
0,56,0,2,1,2,2,2,0,0,2,1,37,5,1,27944
1,38,0,0,0,1,0,5,2,1,0,0,10,7,2,21108
2,18,0,3,1,2,0,0,0,0,0,2,9,7,0,8459
3,55,1,0,0,0,2,3,2,1,1,2,9,8,2,21685
4,22,1,2,1,2,0,2,0,2,2,0,13,6,0,15984

In [13]:
X = df.drop('Annual_Premium_Amount', axis=1)

y = df['Annual_Premium_Amount']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    10000 non-null  int64
 1   Gender                 10000 non-null  int64
 2   Region                 10000 non-null  int64
 3   Marital_status         10000 non-null  int64
 4   Physical_Activity      10000 non-null  int64
 5   Stress_Level           10000 non-null  int64
 6   Number Of Dependants   10000 non-null  int64
 7   BMI_Category           10000 non-null  int64
 8   Smoking_Status         10000 non-null  int64
 9   Employment_Status      10000 non-null  int64
 10  Income_Level           10000 non-null  int64
 11  Income_Lakhs           10000 non-null  int64
 12  Medical History        10000 non-null  int64
 13  Insurance_Plan         10000 non-null  int64
 14  Annual_Premium_Amount  10000 non-null  int64
dtypes: int64(15)
memory usage: 1.1 MB

In [15]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = encoder.fit_transform(df[col])

df.head()

,Age,Gender,Region,Marital_status,Physical_Activity,Stress_Level,Number Of Dependants,BMI_Category,Smoking_Status,Employment_Status,Income_Level,Income_Lakhs,Medical History,Insurance_Plan,Annual_Premium_Amount
0,56,0,2,1,2,2,2,0,0,2,1,37,5,1,27944
1,38,0,0,0,1,0,5,2,1,0,0,10,7,2,21108
2,18,0,3,1,2,0,0,0,0,0,2,9,7,0,8459
3,55,1,0,0,0,2,3,2,1,1,2,9,8,2,21685
4,22,1,2,1,2,0,2,0,2,2,0,13,6,0,15984

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=50,
    random_state=42
)

model.fit(X_train, y_train)

joblib.dump(model, "premium_model.pkl", compress=9)

['premium_model.pkl']

In [18]:
pred = model.predict(X_test)

In [19]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

print("R² Score:", r2_score(y_test, pred))

print("MAE:", mean_absolute_error(y_test, pred))

print("RMSE:", mean_squared_error(y_test, pred)**0.5)

R² Score: 0.9768599721762488
MAE: 958.436185
RMSE: 1334.6662965648056

In [20]:
import joblib

joblib.dump(model, "premium_model.pkl")

['premium_model.pkl']

In [21]:
import os

os.listdir()

['.ipynb_checkpoints',
 'app.py',
 'Health_insu_premium.ipynb',
 'Health_insu_premium.xlsx',
 'premium_model.pkl',
 'requirements.txt']

In [22]:
print("R² Score:", r2_score(y_test, pred))

R² Score: 0.9768599721762488

In [25]:
import os

print(os.path.getsize("premium_model.pkl")/(1024*1024))

5.744109153747559